// Auto-generated by generate-translation-keys.ts
// To regenerate, run one of:
//   bunx ts-node scripts/generate-translation-keys.ts
//   npx ts-node scripts/generate-translation-keys.ts
//   bun run scripts/generate-translation-keys.ts
//   npm run generate-translation-keys

export type TranslationKey =
  | "chat"
  | "profile"
  | "configure_title"
  | "configure_keys_title"
  | "preferred_language_label"
  | "preferred_language_placeholder"
  | "spontaneous_label"
  | "spontaneous_placeholder"
  | "never"
  | "always"
  | "reply_frequency"
  | "save"
  | "saved"
  | "copied"
  | "token_info.profile_id"
  | "token_info.chat_id"
  | "token_info.telegram_user_id"
  | "token_info.telegram_username"
  | "token_info.chat_role"
  | "token_info.version"
  | "provider_needed_for"
  | "where_is_my_key"
  | "errors.oh_no"
  | "errors.expired"
  | "errors.not_found"
  | "errors.not_valid"
  | "errors.misconfigured"
  | "errors.fetch_failed"
  | "errors.save_failed"
  | "errors.check_link";