name: PR Verification on Main

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]
    branches:
      - main

concurrency:
  group: verify-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  verify:
    name: Verify PR
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'Locked') &&
      (github.event.action != 'labeled' || github.event.label.name == 'Locked')
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Prepare the access token
        run: |
          if [ "${{ github.event.pull_request.user.login }}" = "dependabot[bot]" ]; then
            echo "TOKEN=${{ secrets.CI_TOKEN_ABOT }}" >> $GITHUB_ENV
          else
            echo "TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove the verified label if present
        uses: actions-ecosystem/action-remove-labels@v1
        continue-on-error: true
        with:
          github_token: ${{ env.TOKEN }}
          labels: Verified

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Label PR as verified
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ env.TOKEN }}
          labels: Verified

      - name: Comment on PR to notify about verification
        env:
          GH_TOKEN: ${{ env.TOKEN }}
        run: gh pr comment ${{ github.event.pull_request.number }} --body "✅ Auto-verified!"

      - name: Remove verified label on failure or cancellation
        if: always() && (failure() || cancelled())
        uses: actions-ecosystem/action-remove-labels@v1
        continue-on-error: true
        with:
          github_token: ${{ env.TOKEN }}
          labels: Verified
