name: Release Push

on:
  push:
    branches:
      - release

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Build
        env:
          VITE_APP_BASE_URL: ${{ vars.VITE_APP_BASE_URL }}
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL }}
          VITE_LANDING_PAGE_URL: ${{ vars.VITE_LANDING_PAGE_URL }}
          VITE_APP_NAME: ${{ vars.VITE_APP_NAME }}
          VITE_APP_NAME_SHORT: ${{ vars.VITE_APP_NAME_SHORT }}
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deployment
        uses: actions/deploy-pages@v4
