name: "Verification"

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint
        run: bun run lint

      - name: Build
        run: bun run build

      - name: Approve Pull Request
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        env:
          GH_TOKEN: ${{ secrets.CI_TOKEN_ABOT }}
        run: |
          gh pr review ${{ github.event.pull_request.number }} --approve -b "Build passed. Automatically approved by verification workflow."

      - name: Add Verified label to Dependabot PR
        if: github.event.pull_request.user.login == 'dependabot[bot]'
        env:
          CI_TOKEN_ABOT: ${{ secrets.CI_TOKEN_ABOT }}
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ env.CI_TOKEN_ABOT }}
          labels: Verified
